name: Publish to PyPI
on:
  # release:
  #   types: [published]
  push:
    branches:
      - master

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - name: Configure poetry for publishing
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish package to PyPI
        # run: poetry publish --build
        run: echo "Published"
